language: node
install:
  - make bootstrap
  - curl -O http://saucelabs.com/downloads/Sauce-Connect-latest.zip
  - unzip Sauce-Connect-latest.zip
  - java -jar Sauce-Connect.jar $SAUCE_USERNAME $SAUCE_ACCESS_KEY -i $TRAVIS_JOB_ID
  -f CONNECTED &
  - JAVA_PID=$!
before_script:
  - bash -c "while [ ! -f CONNECTED ]; do sleep 2; done"
script:
  - make test
